## Vaishnavi
2224015- S.Y.

In [1]:
import numpy as np

Array of 10 zeroes

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Array of 10 ones

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Array of 10 fives

In [5]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

Array of the integers from 10 to 50

In [6]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Array of all the even integers from 10 to 50

In [7]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

3x3 matrix with values ranging from 0 to 8

In [8]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

3x3 identity matrix

In [9]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Random number between 0 and 1

In [10]:
np.random.rand(1)

array([0.64405599])

Array of 25 random numbers sampled from a standard normal distribution

In [11]:
np.random.randn(25)

array([-1.65384577e-01, -1.03159227e+00,  1.95347159e+00, -3.32139890e-02,
       -6.62795637e-01, -6.54298835e-01,  1.40608478e+00, -2.21319231e-01,
        7.90303487e-01, -8.67459433e-01, -1.71081603e+00,  2.98781090e-01,
       -6.78556551e-01,  6.09538018e-01, -9.34529119e-01, -6.87773317e-01,
        2.59396348e-01,  2.31553459e+00, -1.47454549e-03, -4.28825595e-02,
        3.72173969e-02,  1.09793231e+00, -1.27106956e+00,  3.28845894e-01,
       -5.48388195e-01])

Create the following matrix:

In [12]:
arr=((np.array([i for i in range(1,101)]))/100).reshape(10,10)
arr

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

Array of 20 linearly spaced points between 0 and 1:

In [13]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Number Indexing AND Selection

In [14]:
arr=np.arange(1,26).reshape(5,5)

In [15]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [17]:
arr[2:,1:]   ## code the given the output

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [18]:
arr[3,4]

20

In [19]:
arr[:3,1:2]   ## code for the given output

array([[ 2],
       [ 7],
       [12]])

In [20]:
arr[4,:5]   ## code for the given output

array([21, 22, 23, 24, 25])

In [21]:
arr[3:,0:]  ## code for the given output

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Now do the following

In [22]:
np.sum(arr)    ## for sum of the array

325

In [23]:
np.std(arr)    ## standard deviation of the values of aaray

7.211102550927978

In [24]:
np.sum(arr,axis = 1)    ## sum of all the columns of matrix

array([ 15,  40,  65,  90, 115])

In [25]:
arr[:,4:]

array([[ 5],
       [10],
       [15],
       [20],
       [25]])

In [26]:
arr[:,4] + 50

array([55, 60, 65, 70, 75])

## COMPLETED